
version: 2.1

parameters:
  environment:
    type: string
    default: "production"
    enum: ["staging", "production"]

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            echo "Installing dependencies..."
            npm install
      - run:
          name: Run Unit Tests
          command: |
            echo "Running tests on branch: $CIRCLE_BRANCH"
            npm test

